apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-deployer.name" . }}
  namespace: {{ include "app-deployer.namespace" . }}
  labels:
    {{- include "app-deployer.labels" . | nindent 4 }}
  {{- $annotations := include "app-deployer.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app-deployer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-deployer.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "app-deployer.name" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "app-deployer.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
              {{- if .name }}
              name: {{ .name }}
              {{- end }}
            {{- end }}
          {{- if or .Values.env .Values.envValueFrom }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.envValueFrom }}
            - name: {{ .name }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
